version: '3.8'

services:
  backend:
    image: php:8.1-apache
    container_name: backend
    env_file:
      - ../.env  # ارجاع به فایل .env مشترک
    volumes:
      - ../backend:/var/www/html
    ports:
      - "${BACKEND_PORT}:80"
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"

  frontend:
    image: node:16
    container_name: frontend
    env_file:
      - ../.env  # ارجاع به فایل .env مشترک
    volumes:
      - ../frontend:/app
    working_dir: /app
    ports:
      - "${FRONTEND_PORT}:3000"
    command: npm start

  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - ../.env  # ارجاع به فایل .env مشترک
    environment:
      MYSQL_ROOT_PASSWORD: "${BACKEND_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:3306"