version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    env_file:
      - ../.env
    volumes:
      - ../backend:/var/www/html
    ports:
      - "${BACKEND_PORT}:80"
    environment:
      DB_HOST: "${DB_HOST:-db}"
      DB_PORT: "${DB_PORT:-3306}"
      DB_DATABASE: "${DB_DATABASE:-inventory}"
      DB_USERNAME: "${DB_USERNAME:-user}"
      DB_PASSWORD: "${DB_PASSWORD:-password}"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ../.env
    volumes:
      - ../frontend:/app
    working_dir: /app
    ports:
      - "${FRONTEND_PORT}:3000"
    command: npm start
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: "${BACKEND_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:3306"
    restart: always